[DRAFT] refactor : add event handling class
NathPaquet/Infographie_IFT-3100 pull request #85
Opened 2024-03-13 21:01 UTC by NathPaquet

2024-03-14 01:00 UTC, lomar276 requested changes

2024-03-14 01:00 UTC, lomar276 commented on src/scene/scene2D.cpp
> +  // if (!isMouseClickInScene()) {
Avais-tu finis cette partie en commentaire?

2024-03-14 01:00 UTC, lomar276 commented on src/scene/scene3D/scene3D.cpp
> +    return true;
Peut-être avoir à la fin:
```cpp
return found;
```
au lieu de
```cpp
return true;
return false;
```

2024-03-14 01:00 UTC, lomar276 commented on src/scene/scene3D/scene3D.cpp
> +    return false;
Même chose ici

2024-03-14 01:00 UTC, lomar276 commented on src/scene/scene3D/scene3D.cpp
> +    return true;
Même chose ici

2024-03-15 13:58 UTC, cnator1 approved these changes

2024-03-15 14:16 UTC, merged