Hotfix Scene manager
NathPaquet/Infographie_IFT-3100 pull request #87
Opened 2024-03-15 15:58 UTC by lomar276

2024-03-16 17:26 UTC, NathPaquet requested changes
Quelque petit changement pour du naming, mais overall je pense que c'est good ! Je vais faire une revérification pour voir si je spot pas quelque chose d'autre après

2024-03-16 17:26 UTC, NathPaquet commented on src/scene/sceneManager.h
>    void removeCamera(const SceneObject *sceneObject);
On pourrait enlever cette ligne puisqu'on utilise plus la méthode ?

2024-03-16 17:26 UTC, NathPaquet commented on src/scene/sceneManager.cpp
>    auto cameraPtr = this->sceneObjects.front().get();
NIT : Renaming pour sceneObjectPtr, vue qu'on est pas certain que c'est une camera

2024-03-16 17:26 UTC, NathPaquet commented on src/scene/sceneManager.cpp
> +  auto cameraPtr = this->sceneObjects.front().get();
NIT : Renaming pour sceneObjectPtr, vue qu'on est pas certain que c'est une camera

2024-03-16 17:26 UTC, NathPaquet commented on src/scene/sceneManager.cpp
> +  removeCamera(sceneObject);
Pour ici est-ce qu'on devrait pas avoir un naming comme : attemptToRemoveObjectFromCameras

2024-03-16 18:38 UTC, lomar276 commented on src/scene/sceneManager.h
>    void removeCamera(const SceneObject *sceneObject);
Quelle méthode?

2024-03-18 19:48 UTC, NathPaquet commented on src/scene/sceneManager.h
>    void removeCamera(const SceneObject *sceneObject);
RemoveCamera

2024-03-21 18:11 UTC, lomar276 commented on src/scene/sceneManager.h
>    void removeCamera(const SceneObject *sceneObject);
C'est enlevé ;)

2024-03-21 18:44 UTC, merged