Move object
NathPaquet/Infographie_IFT-3100 pull request #88
Opened 2024-03-15 22:52 UTC by lomar276

**Scène 3D:**
- Possible de déplacer un objet en roulant la molette.

**Scène 2D:**
- Possible de déplacer un objet avec les flèches du clavier.

2024-03-16 17:53 UTC, NathPaquet requested changes
Quelque petit NIT, tu me diras ce que tu en penses

2024-03-16 17:53 UTC, NathPaquet commented on src/scene/scene3D/scene3DEventHandler.cpp
> +    this->scene3D->moveObjectWithScroll(mouseArgs.scrollY);
NIT : Est-ce que on devrait avoir un nom de méthode qui explicite plus que la méthode va pas nécessairement bouger un objet ? En effet, si on est pas en train de cliquer sur un objet on va pas le déplacer

2024-03-16 17:53 UTC, NathPaquet commented on src/scene/scene3D/scene3D.h
> +  const float SCROLL_POWER = 2.f;
Mettre la constante ici dans le Constants.h

2024-03-16 17:53 UTC, NathPaquet commented on src/scene/scene2D/scene2D.cpp
> +  for (const auto &sceneObject : sceneManager.get()->getSelectedObjects()) {
```suggestion
  for (const auto &selectedSceneObject : sceneManager.get()->getSelectedObjects()) {
```

2024-03-16 17:53 UTC, NathPaquet commented on src/scene/scene2D/scene2D.cpp
> +void Scene2D::moveObjectWithKey(int key) {
```suggestion
void Scene2D::moveSelectedObjectsWithKey(int key) {
```

2024-03-16 17:53 UTC, NathPaquet commented on src/scene/scene2D/scene2DEventHandler.cpp
> +}
Ici à voir si on voudrait éventuellement pouvoir bouger la caméra si on a pas d'objet de sélectionné

2024-03-16 17:53 UTC, NathPaquet commented on src/scene/scene.h
> +  SceneObject *draggedObject = nullptr;
Bon catch !

2024-03-20 18:05 UTC, cnator1 approved these changes

2024-03-21 18:44 UTC, merged