Feat/add cubemap
NathPaquet/Infographie_IFT-3100 pull request #89
Opened 2024-03-27 16:37 UTC by NathPaquet

2024-04-02 13:02 UTC, cnator1 commented on src/scene/cubemap/skybox.cpp
> +  this->cubemapTexture.setCubemapTexturePath(Constants::CUBEMAP_TEXTURE_SKYBOX_LIGHTBLUE);
on utilise le `skyboxShader` pour faire le dessin, mais actuellement il y a 2 entité qui load les texture le cubemap et le skyboxShader,  je ne vois pas l'utilité du cubemapTexture mise a part la partie threading pour afficher le loading screen. Peux-tu m'expliquer le role du `cubemapTexture `?

2024-04-02 13:03 UTC, cnator1 commented on src/scene/cubemap/skybox.cpp
> +  if (this->cubemapTexture.enableCubemapTextures()) {
ahh on load ici okok, est-ce que l'objet skybox pourrait possédé sa propre texture alors ?

2024-04-02 13:04 UTC, cnator1 commented on src/scene/scene3D/scene3D.cpp
> +    this->skybox.draw(100, cameraPosition);
est-ce qu'on peut extraire le 100 ici dans une constante

2024-04-02 13:07 UTC, cnator1 commented on bin/data/shaders/skybox.frag
> +    fragColor = texture(skybox, texCoord);
man je comprend rien ahahah

2024-04-02 13:39 UTC, NathPaquet commented on src/scene/scene3D/scene3D.cpp
> +    this->skybox.draw(100, cameraPosition);
Absolument ! Je vais update ça

2024-04-02 13:40 UTC, NathPaquet commented on bin/data/shaders/skybox.frag
> +    fragColor = texture(skybox, texCoord);
Same
Il est expliquer dans ça par contre : https://learnopengl.com/Advanced-OpenGL/Cubemaps

2024-04-05 02:22 UTC, lomar276 requested changes

2024-04-07 19:14 UTC, cnator1 approved these changes

2024-04-08 18:07 UTC, NathPaquet commented on src/ofApp.cpp
> +    if (ImGui::Selectable("Red galaxy", selected == 0)) {
On pourrait utiliser une enum, mais le selected c'est simplement pour l'affichage du selectable des menu de ImGui.

Donc, c'est simplement pour savoir lequel des items dans notre menu qui est selectionner présentement. On pourrait le voir comme un index

2024-04-08 18:34 UTC, NathPaquet commented on src/scene/cubemap/cubemap.cpp
> +  if (!image1 || !image2 || !image3 || !image4 || !image5 || !image6) {
Je ne peux pas utiliser identity puisqu'on utilise c++ 17 et non c++ 20 :(

2024-04-10 02:34 UTC, merged